export const visGraphData = {
  id: 1,
  name: 'Node 1',
  path: 'Path To Node 1',
  type: 'component',
  roots: [
    {
      id: 3,
      name: 'Node 3',
      path: 'Path To Node 3',
      type: 'page',
      roots: [],
      parents: [],
    },
    {
      id: 4,
      name: 'Node 4',
      path: 'Path To Node 4',
      type: 'page',
      roots: [],
      parents: [],
    },
    {
      id: 7,
      name: 'Node 7',
      path: 'Path To Node 7',
      type: 'page',
      roots: [],
      parents: [],
    },
    {
      id: 8,
      name: 'Node 8',
      path: 'Path To Node 8',
      type: 'page',
      roots: [],
      parents: [],
    },
  ],
  parents: [
    {
      id: 2,
      name: 'Node 2',
      path: 'Path To Node 2',
      type: 'component',
      roots: [
        {
          id: 4,
          name: 'Node 4',
          path: 'Path To Node 4',
          type: 'page',
          roots: [],
          parents: [],
        },
        {
          id: 7,
          name: 'Node 7',
          path: 'Path To Node 7',
          type: 'page',
          roots: [],
          parents: [],
        },
      ],
      parents: [
        {
          id: 4,
          name: 'Node 4',
          path: 'Path To Node 4',
          type: 'page',
          roots: [],
          parents: [],
        },
        {
          id: 5,
          name: 'Node 5',
          path: 'Path To Node 5',
          type: 'component',
          roots: [
            {
              id: 7,
              name: 'Node 7',
              path: 'Path To Node 7',
              type: 'page',
              roots: [],
              parents: [],
            },
          ],
          parents: [
            {
              id: 6,
              name: 'Node 6',
              path: 'Path To Node 6',
              type: 'component',
              roots: [
                {
                  id: 7,
                  name: 'Node 7',
                  path: 'Path To Node 7',
                  type: 'page',
                  roots: [],
                  parents: [],
                },
              ],
              parents: [
                {
                  id: 7,
                  name: 'Node 7',
                  path: 'Path To Node 7',
                  type: 'page',
                  roots: [],
                  parents: [],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 3,
      name: 'Node 3',
      path: 'Path To Node 3',
      type: 'page',
      roots: [],
      parents: [],
    },
    {
      id: 8,
      name: 'Node 8',
      path: 'Path To Node 8',
      type: 'page',
      roots: [],
      parents: [],
    },
  ],
}
